import os
from yt_dlp import YoutubeDL
from youtube_list import *

# List of video URLs
# video_urls = [
    # "https://youtu.be/EspLvzAb22M",
    # "https://youtu.be/6BrqGl9rIK0",
    # "https://youtu.be/hV-WhybKilg",
    # "https://youtu.be/RRrf6_VpGz8",
    # "https://youtu.be/Iw-C6QMXdGc",
    # "https://youtu.be/tGo6Wy9lZv0",
    # "https://youtu.be/MmqKkcVRd1w",
    # "https://youtu.be/zBihFcDwzgk",
    # "https://youtu.be/RT3HE5rEiKo",
    # "https://youtu.be/nKT1gvQGir4",
    # "https://youtu.be/DPdcOodwh0s",
    # "https://youtu.be/monCTqmAAOQ",
    # "https://youtu.be/4MgKyR19kMg",
    # "https://youtu.be/Zg_81fObFIw",
    # "https://youtu.be/X1KAglEK_Ig",
    # "https://youtu.be/vypk3Kq3N_Q",
    # "https://youtu.be/CvyoUf1QzTg",
    # "https://youtu.be/Mc7aeNvEZNk",
    # "https://youtu.be/YeDHA1IvkJQ",
    # "https://youtu.be/MOu_fjohOg0",
    # "https://youtu.be/5v84aUFp2tI",
    # "https://youtu.be/YD7ylbYCQ14",
    # "https://youtu.be/Q5prVf_JBJs",
    # "https://youtu.be/-b_Hs0P29hQ",
    # "https://youtu.be/SotwaVnrx44",
    # "https://youtu.be/kcm-wi_R_yQ",
    # "https://youtu.be/SgWUyYDmqKI",
    # "https://youtu.be/gYkVrXHx-5o",
    # "https://youtu.be/hEk4RDBIE38",
    # "https://youtu.be/0lA2dih88wo",
    # "https://youtu.be/pMyE-98Z5qc",
    # "https://youtu.be/Sx8kOo9ifYc",
    # "https://youtu.be/xhfniRFDw7Q",
    # "https://youtu.be/0LDedKaUPdY",
    # "https://youtu.be/nb7jn434X9E",
    # "https://youtu.be/ohmlecNS4dk",
    # "https://youtu.be/DSpFjx2Bh2Y",
    # "https://youtu.be/8-AjG9vpjWg?si=d1OL_kHxSilOblYo",
    # "https://youtu.be/eHsWVd6HHOg",
    # "https://youtu.be/qZ7rol-spP8",
    # "https://youtu.be/2nn9eRjIudM",
    # "https://youtu.be/q4nPTX94X-Y",
    # "https://youtu.be/wXLg88TScYE",
    # "https://youtu.be/644QLZb72Uw",
    # "https://youtu.be/H6KKPdcxq7c",
    # "https://youtu.be/y7JijSqh78M",
    # "https://youtu.be/Z2AbuerLfpE",
    # "https://youtu.be/-IiOQKz8Qj8",
    # "https://youtu.be/fLaZlZMqq6M",
    # "https://youtu.be/11NVhCiDTlo",
    # "https://youtu.be/03bpW0nuqH4",
    # "https://youtu.be/ZtHpEY5TXNI",
    # "https://youtu.be/_-7p7N2hV2I",
    # "https://youtu.be/Yl2wDknfIQw",
    # "https://youtu.be/ErNZzE2KepM",
    "https://youtu.be/GlecgwSqVew",
    "https://youtu.be/sPVhGECgGbw",
    "https://youtu.be/GiyswAkU238",
    "https://youtu.be/dfuM6vzeT34",
    "https://youtu.be/ZjMv-rbaUy4",
    "https://youtu.be/qKvxOrW3bU8",
    "https://youtu.be/Y37ZMLAr4xc",
    "https://youtu.be/EJiiQ6z4wZI",
    "https://youtu.be/opaN-J16rmI",
    "https://youtu.be/awdN3Z62-_Y",
    "https://youtu.be/4v70zzyqvX4", # loop tamborim
    "https://youtu.be/_u_jQEHRykI"
]



# List of video URLs
video_urls = [
    ("https://youtu.be/EspLvzAb22M", "Módulo 2 | semana 1 | aula 1"),
    ("https://youtu.be/6BrqGl9rIK0", "Módulo 2 | semana 1 | aula 2"),
    ("https://youtu.be/RRrf6_VpGz8", "Módulo 2 | semana 2 | aula 1"),
    ("https://youtu.be/hV-WhybKilg", "Módulo 2 | semana 2 | aula 2"),
    ("https://youtu.be/Iw-C6QMXdGc", "Módulo 2 | semana 3 | aula 1"),
    ("https://youtu.be/tGo6Wy9lZv0", "Módulo 2 | semana 3 | aula 2"),
    ("https://youtu.be/zBihFcDwzgk", "Módulo 2 | semana 4 | aula 1"),
    ("https://youtu.be/MmqKkcVRd1w", "Módulo 2 | semana 4 | aula 2"),
    ("https://youtu.be/RT3HE5rEiKo", "Módulo 2 | semana 5 | aula1"),
    ("https://youtu.be/nKT1gvQGir4", "Módulo 2 | semana 5 | aula 2"),
    ("https://youtu.be/monCTqmAAOQ", "Módulo 2 | semana 6 | aula 1"),
    ("https://youtu.be/DPdcOodwh0s", "Módulo 2 | semana 6 | aula 2"),
    ("https://youtu.be/4MgKyR19kMg", "Módulo 2 | semana 7 | aula 1"),
    ("https://youtu.be/Zg_81fObFIw", "Módulo 2 | semana 7 | aula 2"),
    ("https://youtu.be/X1KAglEK_Ig", "Módulo 2 | semana 8 | aula 2"),
    ("https://youtu.be/vypk3Kq3N_Q", "Módulo 2 | semana 8 | aula 1"),
    ("https://youtu.be/CvyoUf1QzTg", "Módulo 3 | semana 1 | aula 1 "),
    ("https://youtu.be/Mc7aeNvEZNk", "Módulo 3 | semana 1 | aula 2"),
    ("https://youtu.be/MOu_fjohOg0", "Módulo 3 | semana 2 | aula 1"),
    ("https://youtu.be/YeDHA1IvkJQ", "Módulo 3 | semana 2 | aula 2"),
    ("https://youtu.be/5v84aUFp2tI", "Módulo 3 | semana 3 | aula 1"),
    ("https://youtu.be/YD7ylbYCQ14", "Módulo 3 | semana 3 | aula 2"),
    ("https://youtu.be/Q5prVf_JBJs", "Módulo 3 | semana 4 | aula 2"),
    ("https://youtu.be/-b_Hs0P29hQ", "Módulo 3 | semana 4 | aula 1"),
    ("https://youtu.be/SotwaVnrx44", "Aula complementar | Módulo 3 | semana 4 | aula 1"),
    ("https://youtu.be/kcm-wi_R_yQ", "Módulo 3 | semana 5 | aula 1"),
    ("https://youtu.be/SgWUyYDmqKI", "Módulo 3 | semana 5 | aula 2"),
    ("https://youtu.be/hEk4RDBIE38", "Módulo 3 | semana 6 | aula 1"),
    ("https://youtu.be/gYkVrXHx-5o", "Módulo 3 | semana 6 | aula 2"),
    ("https://youtu.be/0lA2dih88wo", "Módulo 3 | semana 7 | aula 1"),
    ("https://youtu.be/pMyE-98Z5qc", "Módulo 3 | semana 7 | aula 2"),
    ("https://youtu.be/Sx8kOo9ifYc", "Módulo 3 | semana 8 | aula 2"),
    ("https://youtu.be/xhfniRFDw7Q", "Módulo 3 | semana 8 | aula 1"),
    ("https://youtu.be/0LDedKaUPdY", "Módulo 4 | semana 1 | aula 1"),
    ("https://youtu.be/nb7jn434X9E", "Módulo 4 | semana 1 | aula 2"),
    ("https://youtu.be/ohmlecNS4dk", "Módulo 4 | semana 2 | aula 2"),
    ("https://youtu.be/DSpFjx2Bh2Y", "Módulo 4 | semana 2 | aula 1"),
    ("https://youtu.be/8-AjG9vpjWg?si=d1OL_kHxSilOblYo", "Não escreva! Aula Complementar."),
    ("https://youtu.be/eHsWVd6HHOg", "Módulo 4 | semana 3 | aula 1"),
    ("https://youtu.be/qZ7rol-spP8", "Módulo 4 | semana 3 | aula 2"),
    ("https://youtu.be/2nn9eRjIudM", "Módulo 4 | semana 4 | aula 2"),
    ("https://youtu.be/q4nPTX94X-Y", "Módulo 4 | semana 4 | aula 1"),
    ("https://youtu.be/wXLg88TScYE", "Módulo 4 | semana 5 | aula 1"),
    ("https://youtu.be/644QLZb72Uw", "Módulo 4 | semana 5 | aula 2"),
    ("https://youtu.be/H6KKPdcxq7c", "Módulo 4 | semana 6 | aula 2"),
    ("https://youtu.be/y7JijSqh78M", "Módulo 4 | semana 6 | aula 1"),
    ("https://youtu.be/Z2AbuerLfpE", "Módulo 4 | semana 7 | aula 1"),
    ("https://youtu.be/-IiOQKz8Qj8", "Módulo 4 | semana 7 | aula 2"),
    ("https://youtu.be/fLaZlZMqq6M", "Módulo 4 | semana 8 | aula 1"),
    ("https://youtu.be/11NVhCiDTlo", "Módulo 4 | semana 8 | aula 2"),
    ("https://youtu.be/03bpW0nuqH4", "Módulo 4 | semana 9 | aula única"),
    ("https://youtu.be/ZtHpEY5TXNI", "Módulo 5 | semana 1 | aula 1 ok"),
    ("https://youtu.be/_-7p7N2hV2I", "Módulo 5 | semana 1 | Avançado"),
    ("https://youtu.be/Yl2wDknfIQw", "Módulo 5 | semana 1 | aula 2"),
    ("https://youtu.be/GlecgwSqVew", "Módulo 5 | semana 2 | aula 1"),
    ("https://youtu.be/ErNZzE2KepM", "Módulo 5 | semana 2 | aula 2"),
    ("https://youtu.be/sPVhGECgGbw", "Módulo 5 | semana 2 | avançado"),
    ("https://youtu.be/GiyswAkU238", "Módulo 5 | semana 3 | aula 1"),
    ("https://youtu.be/dfuM6vzeT34", "Módulo 5 | semana 3 | aula 2"),
    ("https://youtu.be/ZjMv-rbaUy4", "Módulo 5 | semana 4 | aula 2"),
    ("https://youtu.be/qKvxOrW3bU8", "Módulo 5 | semana 4 | aula 1"),
    ("https://youtu.be/Y37ZMLAr4xc", "Módulo 5 | semana 2 | aula 1"),
    ("https://youtu.be/EJiiQ6z4wZI", "Módulo 5 | semana 5 | aula 2"),
    ("https://youtu.be/opaN-J16rmI", "Módulo 5 | semana 6 | aula 2"),
    ("https://youtu.be/awdN3Z62-_Y", "Módulo 5 | semana 6 | aula 1"),
    ("https://youtu.be/4v70zzyqvX4", "Loop Tamborim"),
    ("https://youtu.be/_u_jQEHRykI" "Módulo 5 | semana 7 | aula única"),
]


# Path to your cookies file (exported from browser)
cookies_file = "cookies.txt"

# Make sure output folder exists
os.makedirs("videos", exist_ok=True)

# yt-dlp download options
ydl_opts = {
    'outtmpl': 'videos/%(title).70s.%(ext)s',  # Output pattern
    'format': 'bestvideo+bestaudio/best',
    'merge_output_format': 'mp4',
    'quiet': False,
    'noplaylist': False,
    'ignoreerrors': True,
    # 'cookies': cookies_file,
    'cookiesfrombrowser': ('firefox',),
}

# Run downloader
with YoutubeDL(ydl_opts) as ydl:
    ydl.download(video_urls)